BREAK_TOKENS = ['.', ',', ';', '?', '!']
CAPTIONS_FILE_PATH = '/data/captions.vtt'
CAPTIONS_STYLE = 'align:center line:-9 position:50% size:85%'
END_DURATION_OFFSET = 1.5 # in seconds
MAX_CAPTION_LETTERS = 35
MAX_NUM_CAND_SEARCH_ATTEMPTS = 500
MIN_CAPTION_LETTERS = 25
NEW_LINE_TOKENS = ['.', '?', '!']
STORY_FILE_PATH = '/data/story.yaml'
